### ISSUE TITLE
Brunch config options

### ISSUE THREAD

**Issue by soumak77** [hgwood/inject-this-brunch#6]
FYI, this repo may be obsolete.  You can use the brunch plugin config to force plugins to run (http://brunch.io/docs/config#-plugins-).  This would allow using `ng-annotate-brunch` or `ng-annotate-uglify-js-brunch` with your desired use case.

**Comment by soumak77** [comment]
I take that back, the other two libraries don't allow ignoring files, which was causing my build to break due to 3rd party code.

**Comment by soumak77** [comment]
Now sure what is wrong locally in my project, but this plugin seemed to stop working.  Is there some specific way to setup `brunch-config.js` to get this plugin to work?  Brunch isn't compiling the plugin as I had though, so the ES6 syntax is throwing it off when loaded into brunch.

**Comment by hgwood** [comment]
Thanks for your interest. What error are you getting?

**Comment by soumak77** [comment]
``` bash
20 Oct 01:38:57 - warn: Loading of inject-this-brunch failed due to Unexpected token ...
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
20 Oct 01:38:58 - error: Initialization error -  Cannot read property 'brunchPluginName' of null 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
```

**Comment by hgwood** [comment]
Are you using Node.js 6 or greater? If so, can you `Run with``LOGGY_STACKS=true``to see the trace` and post the trace here?

**Comment by soumak77** [comment]
I'm running node v4.4.4.  I'd like to not have to upgrade to v6 just to use this plugin.

```
/Users/brian/GitHub/confidencehr/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/Users/brian/GitHub/confidencehr/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18:9)
  at Promise.all.then.checkDeps.then.out.error.filter.setDefaultJobsCount.constructor.application.loadConfig.then.then.cfg.then.initCompilation.plugins.includes.forEach.initWatcher.chokidar.watch.on.on.absPath.on.compile.assetErrors.forEach.Promise.all.then.then.watch (/Users/brian/GitHub/confidencehr/node_modules/brunch/lib/watch.js:408:15)
  at exports.new.start (/Users/brian/GitHub/confidencehr/node_modules/brunch/lib/index.js:44:10)
  at Command.listener (/Users/brian/GitHub/confidencehr/node_modules/brunch/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/Users/brian/GitHub/confidencehr/node_modules/brunch/node_modules/commander/index.js:615:12)
  at Command.parse (/Users/brian/GitHub/confidencehr/node_modules/brunch/node_modules/commander/index.js:458:21)
  at Object.keys.forEach.exports.run (/Users/brian/GitHub/confidencehr/node_modules/brunch/lib/commands.js:93:11)
  at Object.<anonymous> (/Users/brian/GitHub/confidencehr/node_modules/brunch/lib/run-cli.js:2:18)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

**Comment by hgwood** [comment]
As indicated in [`package.json`](https://github.com/hgwood/inject-this-brunch/blob/master/package.json#L35), this plugin requires Node.js 6 or greater. npm prints a warning on installation if you are not running the correct version. You may fork and tweak the code to make it Node 4-compatible (or [transpile it](https://www.npmjs.com/package/babel-preset-es2015-node4)) if you wish, it should be very easy. Please note [Node 6 has entered LTS while Node 4 will exit LTS in 6 month](https://github.com/nodejs/LTS#lts-schedule).

**Comment by soumak77** [comment]
Thanks for the notes.  I've been meaning to upgrade, but it broke some of the business application I work on last time I tried so I had to stay with v4.  I isolated the issues down to lines 5, 21, and 23.  Would it be possible to re-write those lines so the plugin can work with v4?

If you're willing to accept the PR I can make those changes.
